name: Build and release the app

on:
  push:
    branches: [ "main", "impl_ci" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    name: Create Android Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update version in YAML
        run: sed -i 's/99.99.99/${{ github.ref }}/g' pubspec.yaml
      - name: Create key.properties
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: gradle
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.0"
          channel: 'stable'
          cache: true
      
      - name: Get dependencies
        run: flutter pub get

      - name: Start Android Release Build
        run: flutter build apk --split-per-abi

      - name: Upload Android Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v2
        with:
          name: application
          path: build/app/outputs/apk/release/app-arm64-v8a-release.apk

  release:
    name: Publish the compiled app
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: application
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          name: Aplikacja Connect4Kids wersja ${{ github.ref }}
          token: ${{ secrets.TOKEN }}
          body_path: changelog.md
          files: app-arm64-v8a-release.apk
