name: Build and release the app

on:
  push:
    tags:
      - "*.*.*"
  #pull_request:
  #  branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    name: Create Android Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update version in YAML
        run: sed -i 's/99.99.99/${{ github.ref_name }}/g' pubspec.yaml && cat pubspec.yaml
      - name: Update version in `lib/version.dart`
        run: echo 'const appVersion = "${{ github.ref_name }}";' > lib/version.dart
      - name: Update server url in `lib/gateway_url.dart`
        run: echo 'const gatewayUrl = "https://external.randomscience.org/c4k/api/v1/";' > lib/gateway_url.dart
      - name: Download JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: gradle
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.0"
          channel: 'stable'
          cache: true
      
      - name: Get dependencies
        run: flutter pub get

      - name: Start Android Release Build
        run: flutter build apk --split-per-abi
      - name: Rename app file
        run: mv build/app/outputs/apk/release/app-arm64-v8a-release.apk c4k_daq_v${{ github.ref_name }}.apk
      - name: Upload Android Release
        uses: actions/upload-artifact@v2
        with:
          name: application
          path: c4k_daq_v${{ github.ref_name }}.apk

  release:
    name: Publish the compiled app
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: application
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Aplikacja Connect4Kids wersja ${{ github.ref_name }}
          token: ${{ secrets.TOKEN }}
          body_path: changelog.md
          files: c4k_daq_v${{ github.ref_name }}.apk
